export const CALENDAR_SEVEN_DAY_MIN_WIDTH_PX = 980
const CALENDAR_DAY_COLUMN_MIN_WIDTH_PX = CALENDAR_SEVEN_DAY_MIN_WIDTH_PX / 7
export const TIMED_GRID_TIME_GUTTER_WIDTH_PX = 72

export const getTimedGridMinWidthPx = (dayCount: number) =>
  TIMED_GRID_TIME_GUTTER_WIDTH_PX + CALENDAR_DAY_COLUMN_MIN_WIDTH_PX * dayCount
